#---------------------------------------------------------------------------------------------------------------------------------------#
#100.   Introduction.                                                                                                                   #
#---------------------------------------------------------------------------------------------------------------------------------------#
#   |This function is intended to merge the JS objects represented by the result of [omniR$Visualization$echarts4r.as.tooltip] into one #
#   | JS function, which can thus be rendered by <echarts.tooltip.formatter> in a web session                                           #
#   |-----------------------------------------------------------------------------------------------------------------------------------#
#   |[Scenarios]                                                                                                                        #
#   |-----------------------------------------------------------------------------------------------------------------------------------#
#   |[1] Create vectorized tooltips with multiple charts inside them respectively, for vectorized charts to display in [DT::datatable]  #
#---------------------------------------------------------------------------------------------------------------------------------------#
#200.   Glossary.                                                                                                                       #
#---------------------------------------------------------------------------------------------------------------------------------------#
#   |100.   Parameters.                                                                                                                 #
#   |-----------------------------------------------------------------------------------------------------------------------------------#
#   |...         :   Various data.frames generated by [omniR$Visualization$echarts4r.as.tooltip] as standardization                     #
#   |container   :   Function that takes the same number of arguments as the members in [...], to conduct the concatenation of HTML tags#
#   |                 [<func>      ] <Default> Directly paste all the provided tags into one                                            #
#   |-----------------------------------------------------------------------------------------------------------------------------------#
#   |900.   Return Values by position.                                                                                                  #
#   |-----------------------------------------------------------------------------------------------------------------------------------#
#   |<vec>       :   Character vector that represents JS function to be invoked by <echarts.tooltip.formatter>                          #
#---------------------------------------------------------------------------------------------------------------------------------------#
#300.   Update log.                                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------------------------#
#   | Date |    20220413        | Version | 1.00        | Updater/Creator | Lu Robin Bin                                                #
#   |______|____________________|_________|_____________|_________________|_____________________________________________________________#
#   | Log  |Version 1.                                                                                                                  #
#   |______|____________________________________________________________________________________________________________________________#
#---------------------------------------------------------------------------------------------------------------------------------------#
#400.   User Manual.                                                                                                                    #
#---------------------------------------------------------------------------------------------------------------------------------------#
#   |See the [Full Test Program] section                                                                                                #
#---------------------------------------------------------------------------------------------------------------------------------------#
#500.   Dependent Facilities.                                                                                                           #
#---------------------------------------------------------------------------------------------------------------------------------------#
#   |100.   Dependent Modules                                                                                                           #
#   |-----------------------------------------------------------------------------------------------------------------------------------#
#   |   |magrittr, rlang, dplyr                                                                                                         #
#   |-----------------------------------------------------------------------------------------------------------------------------------#
#   |300.   Dependent functions                                                                                                         #
#   |-----------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------------------------------------------------------------------------#

#001. Append the list of required packages to the global environment
#Below expression is used for easy copy-paste from raw text strings instead of quoted ones.
lst_pkg <- deparse(substitute(c(
	magrittr, rlang, dplyr
)))
#Quote: https://www.regular-expressions.info/posixbrackets.html?wlr=1
lst_pkg <- paste0(lst_pkg, collapse = '')
lst_pkg <- gsub('[[:space:]]', '', lst_pkg, perl = T)
lst_pkg <- gsub('^c\\((.+)\\)', '\\1', lst_pkg, perl = T)
lst_pkg <- unlist(strsplit(lst_pkg, ',', perl = T))
options( omniR.req.pkg = base::union(getOption('omniR.req.pkg'), lst_pkg) )

#Enable pipe operators
library(magrittr)
#Enable big-bang <!!!> operator
library(rlang)

echarts4r.merge.tooltips <- function(
	...
	,container = paste0
){
	#001. Handle parameters
	#[Quote: https://stackoverflow.com/questions/15595478/how-to-get-the-name-of-the-calling-function-inside-the-called-routine ]
	LfuncName <- deparse(sys.call()[[1]])
	#If above statement cannot find the name correctly, this function must have been called via [do.call] or else,
	# hence we need to traverse one layer above current one and extract the first argument of that call.
	if (grepl('^function.+$',LfuncName[[1]],perl = T)) LfuncName <- gsub('^.+?\\((.+?),.+$','\\1',deparse(sys.call(-1)),perl = T)[[1]]

	#015. Function local variables
	dots <- rlang::list2(...)
	var_func <- 'js_func'
	var_tags <- 'html_tags'
	sym_func <- rlang::sym(var_func)
	sym_tags <- rlang::sym(var_tags)

	#100. Add necessary columns to the provided data.frames respectively
	df_trans <- lapply(
		seq_along(dots)
		,function(i){
			dots[[i]] %>%
				#Below JS functions will be defined as global in the web session in terms of JS syntax
				# dplyr::mutate(def_func = paste0('mrgTTChart', i, '_', dplyr::row_number(), ' = ', !!sym_func, ';')) %>%
				# dplyr::mutate(call_func = paste0('mrgTTChart', i, '_', dplyr::row_number(), '();'))
				dplyr::mutate(def_func = paste0('mrgTTChart', i, ' = ', !!sym_func, ';')) %>%
				dplyr::mutate(call_func = paste0('mrgTTChart', i, '();'))
		}
	)

	#200. Prepare functions to initialize the <echarts> objects
	#Combine the dedicated column of all input data.frames into one vector
	func_defs <- eval(rlang::expr(Reduce(paste0, !!lapply(df_trans, function(x){x %>% dplyr::pull(def_func)}))))

	#300. Prepare function calls on initialization of <echarts:tooltip>
	func_calls <- eval(rlang::expr(Reduce(paste0, !!lapply(df_trans, function(x){x %>% dplyr::pull(call_func)}))))

	#500. Combine the HTML tags with the user requested method
	join_tags <- eval(rlang::expr(mapply(
		container
		,!!!lapply(df_trans, function(x){x %>% dplyr::pull(!!sym_tags)})
		,USE.NAMES = FALSE
		,SIMPLIFY = TRUE
	)))

	#900. Create the universal JS statements
	#[JavaScript四种函数调用方式]
	#Quote: https://blog.csdn.net/woaijianjiandandande/article/details/52858326
	paste0(
		'function(params){'
			,func_defs
			,'setTimeout(function () {'
				,func_calls
			,'}, 500);'
			,'var tthtml = ',shQuote(join_tags),';'
			,'return(tthtml);'
		,'}'
	)
}

#[Full Test Program;]
if (FALSE){
	#Not run
	if (FALSE){
		#How to paste all columns of the same data.frame into one character vector on a row basis
		#Quote [#7]: https://stackoverflow.com/questions/68189962/combine-column-values-in-an-r-dataframe-all-at-once
		#[ASSUMPTION]
		#[1] The helper function takes [...] as input, indicating all columns of the input data.frame
		#[2] The result from the function for applying [purrr::pmap_dfr] should have [names] attribute
		#[3] The return value of [purrr::pmap_dfr] is a tibble
		aaa <- data.frame(
			a = c('1','2','3')
			,b = c('4','5','6')
		)
		ttt <- function(...){paste0('(',paste(...,sep = ')('),')')}
		ccc <- aaa %>% purrr::pmap_dfr(~setNames(ttt(...), 'ccc'))
	}

	#Simple test
	if (TRUE){
		#010. Load user defined functions
		source('D:\\R\\autoexec.r')

		#020. Simulate the private environment of Shiny App, to generalize the usage of this function
		uRV <- list()

		#050. Choose theme
		uRV$theme <- 'BlackGold'
		uRV$coltheme <- themeColors(uRV$theme)

		#070. Load the raw data
		myenv <- new.env()
		load(file.path(getOption('path.omniR'), 'Visualization', 'prodprice.rdata'), envir = myenv)
		# View(myenv$ProdPrice)

		#080. Prepare container to draw HTML inside the tooltip of <echarts> object
		jointChart <- function(chart_a, chart_b){
			paste0(''
				#Quote: https://www.runoob.com/css/css-positioning.html
				#Quote: https://www.cnblogs.com/zhuzhenwei918/p/6058457.html
				,'<div style=\'position:relative;display:inline-block;margin:0;padding:0;font-size:0;width:1024px;height:540px;\'>'
					,'<div style=\'display:inherit;position:relative;\'>'
						,chart_a
					,'</div>'
					,'<div style=\'display:inherit;position:absolute;right:0;top:50%;\'>'
						,chart_b
					,'</div>'
				,'</div>'
			)
		}

		#100. Create sample data
		ch_fundprice <- myenv$ProdPrice %>%
			dplyr::group_by(ProdName_CN) %>%
			dplyr::arrange(d_data) %>%
			dplyr::summarise(
				c_currency = dplyr::last(c_currency)
				,pr_min = min(Price, na.rm = T)
				,pr_max = max(Price, na.rm = T)
				,pr_curr = dplyr::last(Price)
				,pr_mean = mean(Price, na.rm = T)
				,ech_line = echarts4r_vec_line(
					Price
					,xAxis = d_data
					#20220413 It is tested that if we manually set [html_id], the chart may not display when hovering over,
					#          hence we should never (or under certain condition?) set it
					# ,html_id = paste0('test_tt_', dplyr::last(dplyr::row_number()))
					,disp_min = '历史最低'
					,disp_max = '历史最高'
					,disp_sym = '当日净值'
					,title = '净值走势'
					,theme = uRV$theme
					,jsFmtFloat = 'toFixed(4)'
					,fmtTTSym = NULL
					,as.tooltip = TRUE
					,as.parts = TRUE
				)
				,.groups = 'keep'
			) %>%
			dplyr::ungroup() %>%
			dplyr::mutate(
				pr_color = ifelse(
					pr_curr >= pr_mean
					, uRV$coltheme[['color']][['chart-bar-incr']]
					, uRV$coltheme[['color']][['chart-bar-decr']]
				)
			) %>%
			dplyr::mutate(
				pr_ech = echarts4r_Capsule(
					pr_min
					,pr_max
					,pr_curr
					,barColor = pr_color
					,symColor = uRV$coltheme[['color']][['chart-sym-light']]
					,disp_min = '历史最低'
					,disp_max = '历史最高'
					,disp_sym = '最新净值'
					,theme = uRV$theme
					,as.tooltip = TRUE
					,as.parts = TRUE
				)
			) %>%
			dplyr::mutate(
				ech_merge = echarts4r.merge.tooltips(
					ech_line
					,pr_ech
					,container = jointChart
				)
			) %>%
			dplyr::mutate(
				pr_text = echarts4r_vec_text(
					pr_curr
					,width = 64
					,theme = uRV$theme
					,jsFmtFloat = 'toFixed(4)'
					,fmtTooltip = ech_merge
				)
			)

		#200. Create a [DT::datatable]
		cols <- c('ProdName_CN','c_currency','pr_curr','pr_text')
		dt_fundprice <- DT::datatable(
			ch_fundprice %>% dplyr::select(tidyselect::all_of(cols))
			#Only determine the columns to be displayed, rather than the columns to extract from the input data
			,colnames = cols
			,width = '100%'
			,class = 'compact display'
			,fillContainer = TRUE
			,escape = FALSE
			,options = list(
				#Setup the styles for the table header
				initComplete = htmlwidgets::JS(paste0(
					# 'function(settings, json){'
					# 	,'$(this.api().table().header()).css({'
					# 		,'"background-color": "#625C54"'
					# 		,',"color": "#FFE8CB"'
					# 		,',"font-family": "\'sans-serif\',\'Microsoft YaHei\'"'
					# 		,',"font-size": "10px"'
					# 	,'});'
					# ,'}'
				))
				#We have to set the [stateSave=F], otherwise the table cannot be displayed completely!!
				,stateSave = FALSE
				,ordering = FALSE
				,scrollX = FALSE
				#[Show N entries] on top left
				,pageLength = 2
				,lengthMenu = c(2,4,10,-1)
			)
		) %>%
			add_datatable_render_code() %>%
			add_deps('echarts4r', 'echarts4r') %>%
			#Below is useful for debugging from console
			htmltools::browsable()

		#500. Export a standalone HTML file
		div_funcprice <- shiny::fluidRow(
			shinydashboardPlus::box(
				width = 12
				,shiny::tags$style(
					type = 'text/css'
					,paste0(''
						,'.box {'
							,'background-color: ',uRV$coltheme[['background-color']][['default']],' !important;'
						,'}'
					)
				)
				,shiny::tagList(
					theme_datatable(theme = uRV$theme, transparent = T)
					,dt_fundprice
				)
			)
		)

		path_rpt <- dirname(thisfile())
		rpt_tpl <- file.path(path_rpt, 'echarts4r_vec_line.Rmd')
		rpt_out <- file.path(path_rpt, 'FundPrice.html')
		rmarkdown::render(
			rpt_tpl
			,output_file = rpt_out
			,params = list(
				dt = div_funcprice
			)
			,envir = new.env(parent = globalenv())
		)

		#900. Create [shinyApp] to render the table
		if (interactive()) {
			library(shiny)

			ui <- shinydashboardPlus::dashboardPage(
				header = shinydashboardPlus::dashboardHeader()
				,sidebar = shinydashboardPlus::dashboardSidebar()
				,body = shinydashboard::dashboardBody(
					shinyjs::useShinyjs()
					,shiny::fluidPage(
						shiny::tags$style(
							type = 'text/css'
							,paste0(''
								,'.main-header .navbar, .main-header .logo {'
									,'background-color: ',uRV$coltheme[['background-color']][['default']],' !important;'
								,'}'
								,'.main-sidebar {'
									,'background-color: ',uRV$coltheme[['background-color']][['default']],' !important;'
								,'}'
								,'.content-wrapper {'
									,'background-color: ',uRV$coltheme[['background-color']][['default']],' !important;'
								,'}'
							)
						)
						,shinydashboardPlus::box(
							width = 12
							,shiny::tags$style(
								type = 'text/css'
								,paste0(''
									,'.box {'
										,'background-color: ',uRV$coltheme[['background-color']][['default']],' !important;'
									,'}'
								)
							)
							,shiny::uiOutput('uDiv_DashTables')
						)
					)
				)
				,controlbar = shinydashboardPlus::dashboardControlbar()
				,title = 'DashboardPage'
			)
			server <- function(input, output, session) {
				output$uDiv_DashTables <- shiny::renderUI({

					shiny::tagList(
						theme_datatable(theme = uRV$theme, transparent = T)
						,dt_fundprice
					)
				})
			}

			shiny::shinyApp(ui, server)
		}
	}
}
