%* French language X4ML commands.                                                        ;

%macro STXR_lang_fr;

  %let sasnote = NOTE;
  %let saswarning = AVERTISSEMENT;
  %let saserror = ERREUR;
    %* Translations of the SAS log keywords NOTE, WARNING and ERROR.                     ;

  %let c = c;
  %let r = l;
  %let alignment = position;
  %let appactivate = app.activer;
  %let appmaximize = app.agrandissement;
  %let average = moyenne;
  %let border = encadrement;
  %let clear = effacer;
  %let columnwidth = largeur.colonne;
  %let copy = copier;
  %let editcolor = modifier.couleur;
  %let error = erreur;
  %let false = faux;
  %let fileclose = fichier.fermer;
  %let filter = filtre;
  %let fontproperties = proprietes.police;
  %let formatfont = format.police;
  %let formatnumber = format.nombre;
  %let formulareplace = remplacer.cellule;
  %let freezepanes = figer.volets;
  %let getdocument = lire.document;
  %let getworkbook = lire.classeur;
  %let halt = arreter;
  %let max = max;
  %let median = mediane;
  %let min = min;
  %let new = nouveau.document;
  %let open = ouvrir;
  %let pastespecial = collage.special;
  %let patterns = motifs;
  %let percentile = centile;
  %let quit = quitter;
  %let rowheight = hauteur.ligne;
  %let run = executer;
  %let saveas = enregistrer.sous;
  %let select = selectionner;
  %let selection = selection;
  %let sendkeys = touches;
  %let sendkeycmd = %{o}{e}{a}%{m}{enter};
    %* Key command to merge two adjacent cells together, meaning                         ;
	%* "ALT+O -> E -> A -> ALT+M -> ENTER", which is equivalent to                       ;
    %* "Format -> Cells -> Alignment -> Merge Cells -> OK" in the English version. Above ;
    %* is just a (probably wrong) guess -- translation still needed for this language.   ;
  %let setname = poser.nom;
  %let setvalue = poser.valeur;
  %let sum = somme;
  %let sumproduct = sommeprod;
  %let true = vrai;
  %let windowmaximize = fenetre.agrandissement;
  %let workbookactivate = activer.classeur;
  %let workbookcopy = copie.classeur;
  %let workbookdelete = supprimer.classeur;
  %let workbookinsert = inserer.classeur;
  %let workbookmove = deplacement.classeur;
  %let workbookname = nommer.classeur;
  %let workbooknext = classeur.suivant;

%mend STXR_lang_fr;
