%* Gives basic information about how to use SASTOXLRPT.                                  ;


%macro STXR_info;

%****************************************************************************************;
%*                                                                                       ;
%* sasToXLrpt version 1.00 -- 2/6/2009                                                   ;
%*                                                                                       ;
%* SOURCE   : sasToXLrpt.sas                                                             ;
%*                                                                                       ;
%* PURPOSE  : To pour the contents of a SAS data set into a MS Excel spreadsheet using   ;
%*            Dynamic Data Exchange (DDE). The resulting spreadsheet receives either no  ;
%*            formatting, some basic formatting, or elaborate formatting (depending on   ;
%*            certain parameters) and is saved to a specified location.  An existing,    ;
%*            possibly pre-formatted Excel file can also be written to. Custom sheet     ;
%*            names are supported.                                                       ;
%*                                                                                       ;
%* CREATED  : 08DEC1999 by Koen Vyverman                                                 ;
%*                                                                                       ;
%* MODIFIED : 02JUN2009 by Lu Robin Bin                                                  ;
%*              Re-wrote some of the macro decision code in a more canonical form that   ;
%*              will ensure proper SASv8 functioning.                                    ;
%*                                                                                       ;
%*            04JAN2001 by Koen Vyverman                                                 ;
%*              Added quite a slab of code to take care of custom sheet-names in the     ;
%*              output spreadsheet. Introduced some long filenames in the process, so    ;
%*              this now no longer works with SAS v6.12 and earlier ... Can be easily    ;
%*              repaired though if necessary. In the same go, removed all traces of the  ;
%*              early WAPTWAP methodology for resolving macro-variables before throwing  ;
%*              them at the DDE-link. Now, resolution is forced by means of dummy        ;
%*              text-variables (see DDECMD and MACCMD in the code ...).                  ;
%*                                                                                       ;
%*            17SEP2007 by Nate Derby                                                    ;
%*              Completely revamped the code, as documented at http://exportToXL.sf.net. ;
%*                                                                                       ;
%* USAGE    : Parameters (further defined at http://exportToXL.sourceforge.net/Usage):   ;
%*                                                                                       ;
%*            libin              : Name of the SAS library where the input data set is   ;
%*            (optional)           located. Default = work.                              ;
%*                                                                                       ;
%*            dsin               : Name of the SAS data set, (part of) which needs to be ;
%*            (required)           dumped into Excel.                                    ;
%*                                                                                       ;
%*            cell1row/cell1col  : Row/column number of the first cell of the Excel      ;
%*            (optional)           spreadsheet where data should be inserted - i.e., the ;
%*                                 upper left of the output data range. Default: 1.      ;
%*                                                                                       ;
%*            nrows/ncols:       : Number of rows/columns to be inserted. If none is     ;
%*            (optional)           specified, all rows/columns will be specified, unless ;
%*                                 that value exceeds maximal number allowed by Excel.   ;
%*                                                                                       ;
%*                                                                                       ;
%*            tmplpath/tmplname  : Full directory path/name of the Excel workbook into   ;
%*            (optional)           which the data will be written. If either value is    ;
%*                                 omitted or does not exist, a standard new workbook    ;
%*                                 will be created with one standard worksheet.          ;
%*                                                                                       ;
%*            tmplsheet          : Name of the specific worksheet within TMPLNAME into   ;
%*            (optional)           which data will be written, used only if TMPLPATH and ;
%*                                 TMPLNAME are both given and exist. If the value is    ;
%*                                 omitted or does not exist, a standard new worksheet   ;
%*                                 will be used.                                         ;
%*                                                                                       ;
%*            deletetmplsheet    : Whether TMPLSHEET should be deleted from the workbook ;
%*            (optional)           after it is used. Default: no.                        ;
%*                                                                                       ;
%*            savepath/savename  : Full directory path/name where the finalized Excel    ;
%*            (optional)           workbook will be saved. Default: c:\temp and          ;
%*                                 exportToXL Output.                                    ;
%*                                                                                       ;
%*            sheet              : Two meanings, depending on if TMPLPATH, TMPLNAME and  ;
%*            (optional)           TMPLSHEET are all given and exist:                    ;
%*                                   If yes: TMPLSHEET is renamed as SHEET and moved to  ;
%*                                     the end of the workbook.                          ;
%*                                   If no: SHEET is the name of the specific worksheet  ;
%*                                     of the Excel workbook where the data will be      ;
%*                                     written. If this worksheet already exists, it     ;
%*                                     will be (partially) overwritten.                  ;
%*                                 Default: SheetN, where 'Sheet' is in language         ;
%*                                 specified by LANG (below) and 'N' is smallest         ;
%*                                 positive integer not yet in use in the workbook.      ;
%*                                                                                       ;
%*            wsformat           : The worksheet format, as explained at the website     ;
%*            (optional)           above. Default: default.                              ;
%*                                                                                       ;
%*            lang               : The language of the Excel application. EXPORTTOXL     ;
%*            (optional)           will not work if this is set incorrectly!             ;
%*                                 Default: en (English).                                ;
%*                                                                                       ;
%*            sumvars/statvars   : List of variables in DSIN for which a sum/summary     ;
%*            (optional)           statistics should be listed at the bottom.            ;
%*                                 Default: (none).                                      ;
%*                                                                                       ;
%*            weightvar          : Variable used as the weight variable for the weighted ;
%*            (optional)           average in the summary statistics - ignored if        ;
%*                                 STATVARS is not given or does not exist.              ;
%*                                 Default: (none).                                      ;
%*                                                                                       ;
%*            mergeacross/       : How many cells should be merged across/down over the  ;
%*            mergedown            range of the data.                                    ;
%*            (optional)           Default: 1.                                           ;
%*                                                                                       ;
%*            exporttmplifempty  : Should TMPLSHEET be exported if DSIN is empty?        ;
%*            (optional)           Default: no.                                          ;
%*                                                                                       ;
%*            exportheaders      : Should the headers be exported?                       ;
%*            (optional)           Default: yes.                                         ;
%*                                                                                       ;
%*            exportvarfmts      : Should the variable formats be exported?              ;
%*            (optional)           Default: yes.                                         ;
%*                                                                                       ;
%*            endclose           : Should Excel be closed after exporting the data?      ;
%*            (optional)           Default: yes.                                         ;
%*                                                                                       ;
%*            varheader          : At each position that a value or a table would be     ;
%*            (necessary)          placed, there should be a mark telling this macro to  ;
%*                                 pour the data correctly. There can be more than one   ;
%*                                 header for the macro to recognize, such as "Gvar      ;
%*                                 Gfld Gdat" at this time. "Gvar" and "Gfld" will be    ;
%*                                 recognized as a single value, while elses will be     ;
%*                                 considered as a data table.                           ;
%*                                 Default: Gvar.                                        ;
%*                                                                                       ;
%*            rptWSSuffix        : Beyond a template WorkSheet, the report will be       ;
%*            (optional)           generated in a new one (but maybe of the same name).  ;
%*                                 If the report worksheet name is not the same as the   ;
%*                                 template worksheet, please define the suffix here.    ;
%*                                 And the new name is the template worksheet name plus  ;
%*                                 your suffix.                                          ;
%*                                 Default: (No suffix, so that the report sheet name is ;
%*                                          the same as the template sheet name ).       ;
%*                                                                                       ;
%* EXAMPLES : 1) WORK.SOMETHING needs to be exported and saved to                        ;
%*               'c:\temp\Some data&EnviroEXT.', which will have one worksheet, named 'Sheet1'  ;
%*               and having standard formatting:                                         ;
%*                 %exportToXL(                                                          ;
%*                              dsin=something,                                          ;
%*                              savepath=c:\temp,                                        ;
%*                              savename=Some Data                                       ;
%*                              );                                                       ;
%*                                                                                       ;
%*            2) Only the first 125 rows of WORK.SOMETHING need to be exported to an     ;
%*               existing Excel spreadsheet, 'n:\sasok\data\blank dox\Serious Fun&EnviroEXT.',  ;
%*               and saved as 'c:\temp\Some data&EnviroEXT.'. The block of data is wanted at    ;
%*               row 37, column 3 of a worksheet named 'Stuff from SAS'. If a worksheet  ;
%*               of this name does not already exist, it should be added as an extra     ;
%*               worksheet:                                                              ;
%*                 %exportToXL(                                                          ;
%*                              dsin=something,                                          ;
%*                              cell1row=37,                                             ;
%*                              cell1col=3,                                              ;
%*                              nrows=125,                                               ;
%*                              tmplpath=n:\sasok\data\blank dox,                        ;
%*                              tmplname=Serious Fun,                                    ;
%*                              sheet=Stuff from SAS,                                    ;
%*                              savepath=c:\temp,                                        ;
%*                              savename=Some Data                                       ;
%*                              );                                                       ;
%*                                                                                       ;
%*            3) Many more examples at http://exportToXL.sf.net/Examples                 ;
%*                                                                                       ;
%* CAVEATS  : Specifying either TMPLPATH or TMPLNAME without the other will result in    ;
%*            a standard new document being used.                                        ;
%*                                                                                       ;
%*            Specifying a SHEET that already exists on the target workbook will result  ;
%*            in the content thereof (if any) being at least partially over-written by   ;
%*            the exported SAS data, but this may be what you want!  Pay attention.      ;
%*                                                                                       ;
%*            The names of worksheets in an Excel workbook are _not_ case sensitive,     ;
%*            even if they look as if they are because one is allowed to use mixed case  ;
%*            in the naming. The same goes for the filenames under Windows by the way.   ;
%*                                                                                       ;
%*            EXPORTTOXL will not work if LANG is set incorrectly!                       ;
%*                                                                                       ;
%****************************************************************************************;
                                                                                         
%mend STXR_info;                                                                         
                                                                                         
                                                                                         
                                                                                         
                                                                                         
                                                                                         
                                                                                         
                                                                                         
                                                                                         
                                                                                         
