%* Swedish language X4ML commands.                                                       ;

%macro STXR_lang_sv;

  %let sasnote = MERK;
  %let saswarning = ADVARSEL;
  %let saserror = FEL;
    %* Translations of the SAS log keywords NOTE, WARNING and ERROR.                     ;
    %* Above are guesses -- translations are still needed for this language.             ;

  %let c = c;
  %let r = r;
  %let alignment = justering;
  %let appactivate = app.aktivera;
  %let appmaximize = app.maximera;
  %let average = medel;
  %let border = ram;
  %let clear = ta.bort;
  %let columnwidth = kolumnbredd;
  %let copy = kopiera;
  %let editcolor = redigera.färg;
  %let error = fel;
  %let false = falskt;
  %let fileclose = arkiv.stäng;
  %let filter = filter;
  %let fontproperties = teckensnitt.egenskaper;
  %let formatfont = format.teckensnitt;
  %let formatnumber = format.tal;
  %let formulareplace = formel.ersätt;
  %let freezepanes = lås.fönsterrutor;
  %let getdocument = hämta.dokument;
  %let getworkbook = hämta.arbetsbok;
  %let halt = halt;
  %let max = max;
  %let median = median;
  %let min = min;
  %let new = nytt;
  %let open = öppna;
  %let pastespecial = klistra.in.special;
  %let patterns = mönster;
  %let percentile = percentil;
  %let quit = avsluta;
  %let rowheight = radhöjd;
  %let run = kör.makro;
  %let saveas = spara.som;
  %let select = markera;
  %let selection = markering;
  %let sendkeys = skicka.tangent;
  %let sendkeycmd = %{o}{e}{a}%{m}{enter};
    %* Key command to merge two adjacent cells together, meaning                         ;
	%* "ALT+O -> E -> A -> ALT+M -> ENTER", which is equivalent to                       ;
    %* "Format -> Cells -> Alignment -> Merge Cells -> OK" in the English version. Above ;
    %* is just a (probably wrong) guess -- translation still needed for this language.   ;
  %let setname = ange.namn;
  %let setvalue = ange.värde;
  %let sum = summa;
  %let sumproduct = produktsumma;
  %let true = sant;
  %let windowmaximize = fönster.maximera;
  %let workbookactivate = arbetsbok.aktivera;
  %let workbookcopy = arbetsbok.kopiera;
  %let workbookdelete = arbetsbok.ta.bort;
  %let workbookinsert = arbetsbok.infoga;
  %let workbookmove = arbetsbok.flytta;
  %let workbookname = arbetsboknamn;
  %let workbooknext = arbetsbok.nästa;

%mend STXR_lang_sv;
