%* Norwegian language X4ML commands.                                                     ;

%macro STXR_lang_no;

  %let sasnote = MERK;
  %let saswarning = ADVARSEL;
  %let saserror = FEIL;
    %* Translations of the SAS log keywords NOTE, WARNING and ERROR.                     ;
    %* Above are guesses -- translations are still needed for this language.             ;

  %let c = c;
  %let r = r;
  %let alignment = justering;
  %let appactivate = prog.aktiver;
  %let appmaximize = prog.maksimer;
  %let average = gjennomsnitt;
  %let border = ramme;
  %let clear = fjern;
  %let columnwidth = kolonnebredde;
  %let copy = kopier;
  %let editcolor = rediger.farge;
  %let error = feil;
  %let false = usann;
  %let fileclose = fil.lukk;
  %let filter = filter;
  %let fontproperties = skrift.egenskaper;
  %let formatfont = format.skrift;
  %let formatnumber = format.tall;
  %let formulareplace = formel.erstatt;
  %let freezepanes = frys.segmenter;
  %let getdocument = hent.dokument;
  %let getworkbook = hent.arbeidsbok;
  %let halt = stopp;
  %let max = størst;
  %let median = median;
  %let min = min;
  %let new = nytt;
  %let open = åpne;
  %let pastespecial = lim.inn.utvalg;
  %let patterns = mønster;
  %let percentile = persentil;
  %let quit = avslutt;
  %let rowheight = radhøyde;
  %let run = start.makro;
  %let saveas = lagre.som;
  %let select = merk;
  %let selection = merking;
  %let sendkeys = send.taster;
  %let sendkeycmd = %{o}{e}{a}%{m}{enter};
    %* Key command to merge two adjacent cells together, meaning                         ;
	%* "ALT+O -> E -> A -> ALT+M -> ENTER", which is equivalent to                       ;
    %* "Format -> Cells -> Alignment -> Merge Cells -> OK" in the English version. Above ;
    %* is just a (probably wrong) guess -- translation still needed for this language.   ;
  %let setname = angi.navn;
  %let setvalue = angi.verdi;
  %let sum = summer;
  %let sumproduct = summerprodukt;
  %let true = sann;
  %let windowmaximize = vindu.maksimer;
  %let workbookactivate = arbeidsbok.aktiver;
  %let workbookcopy = arbeidsbok.kopier;
  %let workbookdelete = arbeidsbok.slett;
  %let workbookinsert = arbeidsbok.slett.inn;
  %let workbookmove = arbeidsbok.flytt;
  %let workbookname = arbeidsbok.navn;
  %let workbooknext = arbeidsbok.neste;

%mend STXR_lang_no;
