%* Russian language X4ML commands.                                                       ;

%macro lang_ru;
  
  %let sasnote = NOTE;    
  %let saswarning = WARNING;
  %let saserror = ошибка;   
    %* Translations of the SAS log keywords NOTE, WARNING and ERROR.                     ;
    %* Above are guesses -- translations are still needed for this language.             ;

  %let c = c;
  %let r = r;
  %let alignment = выравнивание;
  %let appactivate = приложение.активизировать;
  %let appmaximize = приложение.развернуть;
  %let average = срзнач;
  %let border = рамка;
  %let clear = стереть;
  %let columnwidth = ширина.столбца;
  %let copy = копировать;
  %let editcolor = правка.цвет;
  %let error = ошибка;
  %let false = ложь;
  %let fileclose = файл.закрыть;
  %let filter = фильтр;
  %let fontproperties = свойства.шрифта;
  %let formatfont = формат.шрифт;
  %let formatnumber = формат.число;
  %let formulareplace = формула.заменить;
  %let freezepanes = фиксировать.подокна;
  %let getdocument = получить.документ;
  %let getworkbook = получить.рабочую.книгу;
  %let halt = стоп;
  %let max = макс;
  %let median = медиана;
  %let min = мин;
  %let new = создать;
  %let open = открыть;
  %let pastespecial = специальная.вставка;
  %let patterns = узоры;
  %let percentile = персентиль;
  %let quit = выход;
  %let rowheight = высота.строки;
  %let run = выполнить;
  %let saveas = сохранить.как;
  %let select = выделить;
  %let selection = выделение;
  %let sendkeys = послать.клавиши;
  %let sendkeycmd = %{o}{e}{a}%{m}{enter};
    %* Key command to merge two adjacent cells together, meaning                         ;
    %* "ALT+O -> E -> A -> ALT+M -> ENTER", which is equivalent to                       ;
    %* "Format -> Cells -> Alignment -> Merge Cells -> OK" in the English version. Above ;
    %* is just a (probably wrong) guess -- translation still needed for this language.   ;
  %let setname = установить.имя;
  %let setvalue = установить.значение;
  %let sum = сумм;
  %let sumproduct = суммпроизв;
  %let true = истина;
  %let windowmaximize = окно.развернуть;
  %let workbookactivate = рабочая.книга.активизировать;
  %let workbookcopy = рабочая.книга.копировать;
  %let workbookdelete = рабочая.книга.удалить;
  %let workbookinsert = поместить.в.рабочуюкнигу;
  %let workbookmove = рабочая.книга.переместить;
  %let workbookname = рабочая.книга.имя;
  %let workbooknext = рабочая.книга.следующая;

%mend lang_ru;
