%* Dutch language X4ML commands.                                                         ;

%macro lang_nl;

  %let sasnote = NOTE;
  %let saswarning = WARNING;
  %let saserror = FOUT;
    %* Translations of the SAS log keywords NOTE, WARNING and ERROR.                     ;
    %* Above are guesses -- translations are still needed for this language.             ;

  %let c = k;
  %let r = r;
  %let alignment = uitlijning;
  %let appactivate = toepassing.activeren;
  %let appmaximize = toepassing.maximumvenster;
  %let average = gemiddelde;
  %let border = rand;
  %let clear = wissen;
  %let columnwidth = kolombreedte;
  %let copy = kopieren;
  %let editcolor = kleur.bewerken;
  %let error = fout;
  %let false = onwaar;
  %let fileclose = bestand.sluiten;
  %let filter = filter;
  %let fontproperties = lettertype.eigenschappen;
  %let formatfont = opmaak.lettertype;
  %let formatnumber = opmaak.getal;
  %let formulareplace = formule.vervangen;
  %let freezepanes = titels.blokkeren;
  %let getdocument = document.lezen;
  %let getworkbook = werkmap.lezen;
  %let halt = stoppen;
  %let max = max;
  %let median = mediaan;
  %let min = min;
  %let new = nieuw;
  %let open = openen;
  %let pastespecial = plakken.speciaal;
  %let patterns = patronen;
  %let percentile = percentiel;
  %let quit = afsluiten;
  %let rowheight = rijhoogte;
  %let run = starten;
  %let saveas = opslaan.als;
  %let select = selecteren;
  %let selection = selectie;
  %let sendkeys = toetsen.verzenden;
  %let sendkeycmd = %{o}{e}{a}%{m}{enter};
    %* Key command to merge two adjacent cells together, meaning                         ;
	%* "ALT+O -> E -> A -> ALT+M -> ENTER", which is equivalent to                       ;
    %* "Format -> Cells -> Alignment -> Merge Cells -> OK" in the English version. Above ;
    %* is just a (probably wrong) guess -- translation still needed for this language.   ;
  %let setname = naam.geven;
  %let setvalue = waarde.bepalen;
  %let sum = som;
  %let sumproduct = somproduct;
  %let true = waar;
  %let windowmaximize = maximumvenster;
  %let workbookactivate = werkmap.activeren;
  %let workbookcopy = kopieren.werkmap;
  %let workbookdelete = werkmap.verwijderen;
  %let workbookinsert = werkmap.invoegen;
  %let workbookmove = werkmap.verplaatsen;
  %let workbookname = werkmap.naam;
  %let workbooknext = werkmap.volgende;

%mend lang_nl;
