%* Italian language X4ML commands.                                                       ;

%macro lang_it;

  %let sasnote = NOTA;
  %let saswarning = AVVERTIMENTO;
  %let saserror = ERRORE;
    %* Translations of the SAS log keywords NOTE, WARNING and ERROR.                     ;

  %let c = c;
  %let r = r;
  %let alignment = formato.allineam;
  %let appactivate = applicaz.attiva;
  %let appmaximize = applicaz.ingrandisci;
  %let average = media;
  %let border = formato.bordo;
  %let clear = modifica.cancella;
  %let columnwidth = formato.largh.colonna;
  %let copy = modifica.copia;
  %let editcolor = opzioni.palette.modifica;
  %let error = errore;
  %let false = falso;
  %let fileclose = file.chiudi;
  %let filter = filtro;
  %let fontproperties = prop.carattere;
  %let formatfont = formato.carattere;
  %let formatnumber = formato.numero;
  %let formulareplace = formula.sostituisci;
  %let freezepanes = opzioni.blocca.riquadri;
  %let getdocument = info.doc;
  %let getworkbook = info.cartella.di.lavoro;
  %let halt = ferma;
  %let max = max;
  %let median = mediana;
  %let min = min;
  %let new = file.nuovo;
  %let open = file.apri;
  %let pastespecial = modifica.incolla.speciale;
  %let patterns = formato.motivi;
  %let percentile = percentile;
  %let quit = file.esci;
  %let rowheight = formato.altezza.riga;
  %let run = macro.esegui;
  %let saveas = file.salva.con.nome;
  %let select = seleziona;
  %let selection = rif.seleziona;
  %let sendkeys = tasti.invia;
  %let sendkeycmd = %{o}{e}{a}%{m}{enter};
    %* Key command to merge two adjacent cells together, meaning                         ;
	%* "ALT+O -> E -> A -> ALT+M -> ENTER", which is equivalent to                       ;
    %* "Format -> Cells -> Alignment -> Merge Cells -> OK" in the English version. Above ;
    %* is just a (probably wrong) guess -- translation still needed for this language.   ;
  %let setname = nome.rif;
  %let setvalue = cella.valore;
  %let sum = somma;
  %let sumproduct = matr.somma.prodotto;
  %let true = vero;
  %let windowmaximize = finestra.ingrandisci;
  %let workbookactivate = cartella.di.lavoro.attiva;
  %let workbookcopy = cartella.di.lavoro.copia;
  %let workbookdelete = cartella.di.lavoro.elimina;
  %let workbookinsert = cartella.di.lavoro.inserisci;
  %let workbookmove = cartella.di.lavoro.muovi;
  %let workbookname = cartella.di.lavoro.nome;
  %let workbooknext = cartella.di.lavoro.succ;

%mend lang_it;
