%* Finnish language X4ML commands.                                                       ;

%macro lang_fi;

  %let sasnote = NOTE;
  %let saswarning = WARNING;
  %let saserror = VIRHE;
    %* Translations of the SAS log keywords NOTE, WARNING and ERROR.                     ;
    %* Above are guesses -- translations are still needed for this language.             ;

  %let c = c;
  %let r = l;
  %let alignment = tasaus;
  %let appactivate = sov.activoi;
  %let appmaximize = sov.suurenna;
  %let average = keskiarvo;
  %let border = reunaviivat;
  %let clear = tyhjennä;
  %let columnwidth = sarakeleveys;
  %let copy = kopioi;
  %let editcolor = muokkaa.väri;
  %let error = virhe;
  %let false = epätosi;
  %let fileclose = tiedosto.sulje;
  %let filter = suodata;
  %let fontproperties = fontti.ominaisuudet;
  %let formatfont = muotoile.fontti;
  %let formatnumber = muotoile.luku;
  %let formulareplace = kaava.korvaa;
  %let freezepanes = kiinnitä.ruudut;
  %let getdocument = nuoda.tied;
  %let getworkbook = nuoda.työkirja;
  %let halt = seis;
  %let max = maks;
  %let median = mediaani;
  %let min = min;
  %let new = uusi;
  %let open = avaa;
  %let pastespecial = liitä.määräten;
  %let patterns = kuviot;
  %let percentile = prosenttipiste;
  %let quit = lopeta;
  %let rowheight = rivikorkeus;
  %let run = suorita;
  %let saveas = tallenna.nimellä;
  %let select = valitse;
  %let selection = valinta;
  %let sendkeys = lähetä.näppäilyt;
  %let sendkeycmd = %{o}{e}{a}%{m}{enter};
    %* Key command to merge two adjacent cells together, meaning                         ;
	%* "ALT+O -> E -> A -> ALT+M -> ENTER", which is equivalent to                       ;
    %* "Format -> Cells -> Alignment -> Merge Cells -> OK" in the English version. Above ;
    %* is just a (probably wrong) guess -- translation still needed for this language.   ;
  %let setname = määritä.arvonimi;
  %let setvalue = määritä.arvo;
  %let sum = summa;
  %let sumproduct = tulojen.summa;
  %let true = tosi;
  %let windowmaximize = ikkuna.suurenna;
  %let workbookactivate = työkirja.aktivoi;
  %let workbookcopy = työkirja.kopioi;
  %let workbookdelete = työkirja.poista;
  %let workbookinsert = työkirja.lisää.taul;
  %let workbookmove = työkirja.siirrä;
  %let workbookname = työkirja.nimi;
  %let workbooknext = työkirja.seuraava;

%mend lang_fi;
