%* Danish language X4ML commands.                                                        ;

%macro lang_da;

  %let sasnote = MERK;
  %let saswarning = ADVARSEL;
  %let saserror = FEJL;
    %* Translations of the SAS log keywords NOTE, WARNING and ERROR.                     ;
    %* Above are guesses -- translations are still needed for this language.             ;

  %let c = c;
  %let r = r;
  %let alignment = justering;
  %let appactivate = prg.aktiver;
  %let appmaximize = prg.maksimer;
  %let average = middel;
  %let border = ramme;
  %let clear = ryd;
  %let columnwidth = kolonnebredde;
  %let copy = kopier;
  %let editcolor = rediger.farve;
  %let error = fejl;
  %let false = falsk;
  %let fileclose = filer.luk;
  %let filter = filter;
  %let fontproperties = skrifttype.egenskaber;
  %let formatfont = formater.skrifttype;
  %let formatnumber = formater.tal;
  %let formulareplace = formel.erstat;
  %let freezepanes = frys.ruder;
  %let getdocument = hent.dokument;
  %let getworkbook = hent.projektmappe;
  %let halt = stop;
  %let max = maks;
  %let median = median;
  %let min = min;
  %let new = ny;
  %let open = åbn;
  %let pastespecial = indsæt.speciel;
  %let patterns = mønstre;
  %let percentile = fraktil;
  %let quit = afslut;
  %let rowheight = rækkehøjde;
  %let run = afspil;
  %let saveas = gem.som;
  %let select = marker;
  %let selection = markering;
  %let sendkeys = send.taster;
  %let sendkeycmd = %{o}{e}{a}%{m}{enter};
    %* Key command to merge two adjacent cells together, meaning                         ;
	%* "ALT+O -> E -> A -> ALT+M -> ENTER", which is equivalent to                       ;
    %* "Format -> Cells -> Alignment -> Merge Cells -> OK" in the English version. Above ;
    %* is just a (probably wrong) guess -- translation still needed for this language.   ;
  %let setname = angiv.navn;
  %let setvalue = angiv.værdi;
  %let sum = sum;
  %let sumproduct = sumprodukt;
  %let true = sand;
  %let windowmaximize = vindue.maksimer;
  %let workbookactivate = projektmappe.aktiver;
  %let workbookcopy = projektmappe.kopier;
  %let workbookdelete = projektmappe.slet;
  %let workbookinsert = projektmappe.indsæt;
  %let workbookmove = projektmappe.flyt;
  %let workbookname = projektmappe.navn;
  %let workbooknext = projektmappe.næste;

%mend lang_da;
