%* Spanish language X4ML commands.                                                       ;

%macro lang_es;

  %let sasnote = NOTA;
  %let saswarning = AVISO;
  %let saserror = ERROR;
    %* Translations of the SAS log keywords NOTE, WARNING and ERROR.                     ;

  %let c = c;
  %let r = l;
  %let alignment = alineacion;
  %let appactivate = apl.activar;
  %let appmaximize = apl.maximizar;
  %let average = promedio;
  %let border = bordes;
  %let clear = borrar;
  %let columnwidth = ancho.columna;
  %let copy = copiar;
  %let editcolor = edicion.color;
  %let error = error;
  %let false = falso;
  %let fileclose = archivo.cerrar;
  %let filter = filtros;
  %let fontproperties = propiedades.fuente;
  %let formatfont = formato.fuentes;
  %let formatnumber = formato.numero;
  %let formulareplace = formula.reemplazar;
  %let freezepanes = inmovilizar.secciones;
  %let getdocument = indicar.documento;
  %let getworkbook = indicar.libro;
  %let halt = detener;
  %let max = max;
  %let median = mediana;
  %let min = min;
  %let new = nuevo;
  %let open = abrir;
  %let pastespecial = pegado.especial;
  %let patterns = diseño;
  %let percentile = percentil;
  %let quit = salir;
  %let rowheight = alto.fila;
  %let run = ejecutar;
  %let saveas = guardar.como;
  %let select = seleccionar;
  %let selection = seleccion;
  %let sendkeys = enviar.teclas;
  %let sendkeycmd = %{o}{e}{a}%{m}{enter};
    %* Key command to merge two adjacent cells together, meaning                         ;
	%* "ALT+O -> E -> A -> ALT+M -> ENTER", which is equivalent to                       ;
    %* "Format -> Cells -> Alignment -> Merge Cells -> OK" in the English version. Above ;
    %* is just a (probably wrong) guess -- translation still needed for this language.   ;
  %let setname = establecer.nombre;
  %let setvalue = establecer.valor;
  %let sum = suma;
  %let sumproduct = sumaproducto;
  %let true = verdadero;
  %let windowmaximize = ventana.maximizar;
  %let workbookactivate = libro.activar;
  %let workbookcopy = libro.copiar;
  %let workbookdelete = eliminar.libro;
  %let workbookinsert = insertar.libro;
  %let workbookmove = libro.mover;
  %let workbookname = nombre.libro;
  %let workbooknext = libro.siguiente;

%mend lang_es;
