%macro cdwmap_CUSTSEG_IMEXtoPSGL(
	inCUSTSEG	=
	,outCUSTSEG	=
);
if &inCUSTSEG.="01" then &outCUSTSEG.="10";
if &inCUSTSEG.="02" then &outCUSTSEG.="12";
if &inCUSTSEG.="03" then &outCUSTSEG.="14";
if &inCUSTSEG.="04" then &outCUSTSEG.="11";
if &inCUSTSEG.="05" then &outCUSTSEG.="13";
if &inCUSTSEG.="06" then &outCUSTSEG.="20";
if &inCUSTSEG.="07" then &outCUSTSEG.="25";
if &inCUSTSEG.="08" then &outCUSTSEG.="26";
if &inCUSTSEG.="09" then &outCUSTSEG.="27";
if &inCUSTSEG.="10" then &outCUSTSEG.="28";
if &inCUSTSEG.="11" then &outCUSTSEG.="300";
if &inCUSTSEG.="12" then &outCUSTSEG.="305";
if &inCUSTSEG.="13" then &outCUSTSEG.="308";
if &inCUSTSEG.="14" then &outCUSTSEG.="309";
if &inCUSTSEG.="15" then &outCUSTSEG.="350";
if &inCUSTSEG.="16" then &outCUSTSEG.="355";
if &inCUSTSEG.="17" then &outCUSTSEG.="358";
if &inCUSTSEG.="18" then &outCUSTSEG.="359";
if &inCUSTSEG.="19" then &outCUSTSEG.="400";
if &inCUSTSEG.="20" then &outCUSTSEG.="408";
if &inCUSTSEG.="21" then &outCUSTSEG.="409";
if &inCUSTSEG.="22" then &outCUSTSEG.="420";
if &inCUSTSEG.="23" then &outCUSTSEG.="428";
if &inCUSTSEG.="24" then &outCUSTSEG.="429";
if &inCUSTSEG.="25" then &outCUSTSEG.="440";
if &inCUSTSEG.="26" then &outCUSTSEG.="448";
if &inCUSTSEG.="27" then &outCUSTSEG.="449";
if &inCUSTSEG.="28" then &outCUSTSEG.="460";
if &inCUSTSEG.="29" then &outCUSTSEG.="468";
if &inCUSTSEG.="30" then &outCUSTSEG.="469";
if &inCUSTSEG.="31" then &outCUSTSEG.="500";
if &inCUSTSEG.="32" then &outCUSTSEG.="505";
if &inCUSTSEG.="33" then &outCUSTSEG.="508";
if &inCUSTSEG.="34" then &outCUSTSEG.="509";
if &inCUSTSEG.="35" then &outCUSTSEG.="600";
if &inCUSTSEG.="36" then &outCUSTSEG.="608";
if &inCUSTSEG.="37" then &outCUSTSEG.="609";
if &inCUSTSEG.="38" then &outCUSTSEG.="630";
if &inCUSTSEG.="39" then &outCUSTSEG.="650";
if &inCUSTSEG.="40" then &outCUSTSEG.="655";
if &inCUSTSEG.="41" then &outCUSTSEG.="658";
if &inCUSTSEG.="42" then &outCUSTSEG.="659";
if &inCUSTSEG.="43" then &outCUSTSEG.="950";
if &inCUSTSEG.="44" then &outCUSTSEG.="960";
if &inCUSTSEG.="45" then &outCUSTSEG.="970";
if &inCUSTSEG.="46" then &outCUSTSEG.="98";
if &inCUSTSEG.="47" then &outCUSTSEG.="97";
if &inCUSTSEG.="48" then &outCUSTSEG.="99";
if &inCUSTSEG.="49" then &outCUSTSEG.="29";
%mend cdwmap_CUSTSEG_IMEXtoPSGL;